In [1]:
import pandas as pd
import math
from statistics import mode 
from sklearn.model_selection import train_test_split
import numpy as np
from sklearn import metrics
from sklearn.neighbors import KNeighborsClassifier
import math
import matplotlib.pyplot as plt

In [118]:
df=pd.read_csv('Cars.csv')

In [3]:
col=list(df.columns)
print("Enter the output column")
inp=input()
col.remove(inp)


Enter the output column
Stolen


In [4]:
for i in col:
    categ=df[i].value_counts().keys()
    for j in categ:
        df.insert(3,j,

SyntaxError: unexpected EOF while parsing (<ipython-input-4-523d7ca7bf31>, line 4)

In [83]:
newCol=[[x+'_'+i for i in df[x].value_counts().keys().tolist()]for x in col]

In [5]:
[df[x].loc[i]==df[x].unique() for (x,i) in zip(col,range(df.shape[0]))]

[array([ True, False]), array([ True, False]), array([ True, False])]

In [24]:
[df[x].loc[i]==df[x].unique() for (x,i) in zip(col,range(df.shape[0]))]

'Red'

In [30]:
ind=len(df.columns)
for i in newCol:
    for j in i:
        k=j.split('_')
        print(np.where(df[k[0]] == k[1]))
        val=(func(np.where(df[k[0]] == k[1])))
        df.insert(ind,j,val)
        ind=ind+1

(array([0, 1, 2, 8, 9], dtype=int64),)
(array([3, 4, 5, 6, 7], dtype=int64),)
(array([0, 1, 2, 3, 4, 9], dtype=int64),)
(array([5, 6, 7, 8], dtype=int64),)
(array([0, 1, 2, 3, 7], dtype=int64),)
(array([4, 5, 6, 8, 9], dtype=int64),)


In [45]:

matrix = [[1, 2, 3], [4, 5], [6, 7, 8, 9]] 
  
flatten_matrix = [] 
  
# for sublist in matrix: 
#     for val in sublist: 
#         flatten_matrix.append(val) 

flatten_matrix = [val for sublist in matrix for val in sublist] 

print(flatten_matrix)

[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [84]:
values=[func(np.where(j.split('_')[1]==df[j.split('_')[0]])) for i in newCol for j in i]
newCol=[j for i in newCol for j in i]

In [96]:
df1 = pd.DataFrame(np.transpose(values),columns=newCol)

In [105]:
df1

Color_Red  Color_Yellow  Type_Sports  Type_Suv  Origin_Domestic  \
0          1             0            1         0                1   
1          1             0            1         0                1   
2          1             0            1         0                1   
3          0             1            1         0                1   
4          0             1            1         0                0   
5          0             1            0         1                0   
6          0             1            0         1                0   
7          0             1            0         1                1   
8          1             0            0         1                0   
9          1             0            1         0                0   

   Origin_Imported  
0                0  
1                0  
2                0  
3                0  
4                1  
5                1  
6                1  
7                0  
8                1  
9                1

In [119]:
df = df.merge(df1,left_index=True, right_index=True)

In [121]:
col

['Color', 'Type', 'Origin']

In [122]:
df.drop(col, axis=1, inplace=True)


In [123]:
df

Stolen  Color_Red  Color_Yellow  Type_Sports  Type_Suv  Origin_Domestic  \
0    Yes          1             0            1         0                1   
1     No          1             0            1         0                1   
2    Yes          1             0            1         0                1   
3    Yes          0             1            1         0                1   
4    Yes          0             1            1         0                0   
5     No          0             1            0         1                0   
6    Yes          0             1            0         1                0   
7     No          0             1            0         1                1   
8     No          1             0            0         1                0   
9    Yes          1             0            1         0                0   

   Origin_Imported  
0                0  
1                0  
2                0  
3                0  
4                1  
5                1  
6                1  
7                0  
8                1  
9                1

In [78]:
np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]),

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),)

In [33]:
def func(arr):
    a=np.zeros(df.shape[0])
    a[arr]=np.ones(len(arr))
    return list(a.astype(int))

In [108]:
new_col=[x+i for i in [df[x].unique() for x in col]]

In [121]:
a=np.zeros(5)

In [122]:
a[0]=1
a

array([1., 0., 0., 0., 0.])

In [9]:
newCol

[['Color_Red', 'Color_Yellow'],
 ['Type_Sports', 'Type_Suv'],
 ['Origin_Domestic', 'Origin_Imported']]

In [125]:
a = np.arange(5)
np.put(a, [0, 2], [-44, -55])

In [12]:
b=np.zeros(df.shape[0])
a=[0, 1, 2, 8, 9]

In [13]:
b[a]=np.ones(len(a))

In [18]:
b[0]

1.0

In [117]:
df

Type    Origin Stolen  Color_Red  Color_Yellow  Type_Sports  Type_Suv  \
0  Sports  Domestic    Yes          1             0            1         0   
1  Sports  Domestic     No          1             0            1         0   
2  Sports  Domestic    Yes          1             0            1         0   
3  Sports  Domestic    Yes          0             1            1         0   
4  Sports  Imported    Yes          0             1            1         0   
5     Suv  Imported     No          0             1            0         1   
6     Suv  Imported    Yes          0             1            0         1   
7     Suv  Domestic     No          0             1            0         1   
8     Suv  Imported     No          1             0            0         1   
9  Sports  Imported    Yes          1             0            1         0   

   Origin_Domestic  Origin_Imported  
0                1                0  
1                1                0  
2                1                0  
3                1                0  
4                0                1  
5                0                1  
6                0                1  
7                1                0  
8                0                1  
9                0                1